### ISSUE TITLE
Sharing your repo

### ISSUE THREAD

**Issue by ddesmond** [BreakTools/deadline-web-app-frontend#1]
Hey!
took a liberty to clone your repo in https://github.com/ddesmond/deadline-container
I hope you dont mind as this completes the docker stack :)

Let me know if its not ok and I will remove it.

Thanks for such a great tool!

Best!

**Comment by mervinvb** [comment]
Hey @ddesmond, somehow this issue slipped past me but I love that you've added my tool to your containerized setup! Definitely keep it in there and keep up the good work :)

Cheers, Mervin
